apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-provisioner
  name: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-provisioner
    spec:
      nodeSelector:
        kubernetes.io/role: master
      serviceAccountName: nfs-pod-provisioner-sa # name of service account created in rbac.yaml
      containers:
        - name: nfs-provisioner
          image: vbouchaud/nfs-client-provisioner
          volumeMounts:
            - name: nfs-provisioner-v
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME # do not change
              value: nfs-storage-class-1 # SAME AS PROVISONER NAME VALUE IN STORAGECLASS
            - name: NFS_SERVER # do not change
              value: 192.168.0.144 # Ip of the NFS SERVER
            - name: NFS_PATH # do not change
              value: /mnt/usb/volume/1/share/kubernetes/ # path to nfs directory setup
      volumes:
        - name: nfs-provisioner-v # same as volumemouts name
          nfs:
            server: 192.168.0.144
            path: /mnt/usb/volume/1/share/kubernetes/